language: python
dist: "xenial"
python:
  - "3.6"
  - "3.7"
before_install:
  - python --version
install:
  - pip install -r requirements-test.txt
  - pip install pytest codecov pytest-cov setuptools-scm
script:
  - pytest --cov=coarij tests/
after_success:
  - codecov
deploy:
  provider: pypi
  user: icoxfog417
  password:
    secure: GE9JHEupOBCgWk5Namo6fX+uMJF1FtazITSuH6pH0p8pqmqBbW+jPapgwvmTY7Cz3YtFI0o+723XI2bL0ZSMccELSm/9WEkCDPmCGpC4awW5HMN6N5/QuSRk5/dL3anwEnsr+FvMIrHy3R3SA/mPbv9mpk6yzaNIoqiT40ipPPd5ZDpLGeFO30CmxvHK729R6o8piOKji1LUOlkUmdwA9RHBUdUITs+vGFngSrsrtJ2iZyAzslWMhTep+C97/e2sDO+sz4SuBJqj75EmAO26eDWc5/x2Gs2vkE3zEBhKYuSxNJPOFnZD/N7FZKlPQtx93ipYX+TeIw2xE3p1wWX11kOuY6quWE2qWh3MFG1JBwJMa3Od/3ERTq23VCds/6PNsuh5mad874VMpsShA7DhxP/0DZaBJusdWdFgoNLPTkwWOcGP7Ix77jnZlwr5QCJkIaEY8RbAmo0locMx3JDQFxDzfIY88UukV/zBzSDDjMqNZ9d4fXnT/MS5WAj/gkAtCjmEJ3VQL1cZ28TsCXubic6XbxbimBlYm0atjGjpNFB/MBJZxm0r/Bxc+UKLDQyx1656q+Hi9RTF9rhtd64Edj2922TxUPxvAGf6hpUAFnzftX9r4A3stitGzh9O5hDqcv+6+/T2s7pXxDZtE1Ic9MMhwXoQ5lFcR9bUBuFDa/Y=
  on:
    tags: true
    python: "3.7"
